# Generated by Django 5.0.6 on 2024-09-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_predictionresult_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
