# Generated by Django 5.0.6 on 2024-08-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0004_generalsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='tagline',
            field=models.CharField(default='Empowering Early Detection, Saving Lives', max_length=255),
        ),
    ]
