# Generated by Django 5.0.6 on 2024-08-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0005_alter_generalsettings_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='allow_registration',
            field=models.BooleanField(db_default=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='company',
            field=models.CharField(db_default='Zila Tech', max_length=255),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='maintenance_mode',
            field=models.BooleanField(db_default=False),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='site_name',
            field=models.CharField(db_default='MyProject', max_length=255),
        ),
    ]
