# Generated by Django 5.0.6 on 2024-08-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0007_delete_emailsettings_delete_generalsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_backend', models.CharField(default='django.core.mail.backends.smtp.EmailBackend', max_length=255)),
                ('email_host', models.CharField(default='smtp.example.com', max_length=255)),
                ('email_port', models.IntegerField(db_default=587)),
                ('email_use_tls', models.BooleanField(db_default=True)),
                ('email_use_ssl', models.BooleanField(db_default=False)),
                ('email_host_user', models.CharField(max_length=255)),
                ('email_host_password', models.CharField(max_length=255)),
                ('default_from_email', models.EmailField(db_default='info.quickdiag@gmail.com', max_length=254)),
                ('email_subject_prefix', models.CharField(db_default='QuickDiag', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(db_default='MyProject', max_length=255)),
                ('company', models.CharField(db_default='Zila Tech', max_length=255)),
                ('tagline', models.CharField(default='Empowering Early Detection, Saving Lives', max_length=255)),
                ('site_description', models.TextField(blank=True, null=True)),
                ('allow_registration', models.BooleanField(db_default=True)),
                ('maintenance_mode', models.BooleanField(db_default=False)),
            ],
        ),
    ]
