# Generated by Django 5.0.6 on 2024-08-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0009_delete_generalsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='MyProject', max_length=255)),
                ('company', models.CharField(default='Zila Tech', max_length=255)),
                ('tagline', models.CharField(default='Empowering Early Detection, Saving Lives', max_length=255)),
                ('site_description', models.TextField(blank=True, null=True)),
                ('allow_registration', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.CharField(default='We are currently undergoing maintenance. We apologize for any inconvenience.', max_length=500)),
                ('maintenance_end_time', models.DateTimeField(blank=True, null=True)),
                ('contact_email', models.EmailField(db_default='info.quickdiag@gmail.com', max_length=254)),
            ],
        ),
    ]
