# Generated by Django 5.0.6 on 2024-08-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0010_generalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='address',
            field=models.CharField(default=' 123 Main Street, Paraku Estate, XEZ', max_length=100),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='telephone',
            field=models.CharField(default='(123) 456-7890', max_length=20),
        ),
    ]
