# Generated by Django 5.0.6 on 2024-08-25 17:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0011_generalsettings_address_generalsettings_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('model_type', models.CharField(max_length=255)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('training_data_path', models.CharField(max_length=500)),
                ('date_trained', models.DateTimeField(auto_now_add=True)),
                ('is_default', models.BooleanField(default=False)),
                ('model_file_path', models.CharField(max_length=500)),
                ('scaler_file_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-date_trained'],
            },
        ),
    ]
