# Generated by Django 5.0.6 on 2024-08-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0012_trainedmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='allowed_hosts',
            field=models.TextField(default='localhost,127.0.0.1'),
        ),
    ]
